#!/bin/zsh

set -x -e

ARCH=$1
DEST=out/$ARCH

case $ARCH in
  win32)
    export PATH="/usr/local/i686-w64-mingw32-20150524.loee.pl/bin:$PATH"
    ARCHPREFIX=i686-w64-mingw32
    CC=$ARCHPREFIX-gcc
    CXX=$ARCHPREFIX-g++
    AR=$ARCHPREFIX-ar
    LIBUDEV=no
    POSIX=no
    cfl=(-DUNICODE -D_UNICODE -m32)
    makelib () {
      $AR rcs "$@"
    }
    ;;
  win64)
    export PATH="/usr/local/x86_64-w64-mingw32-20150524.loee.pl/bin:$PATH"
    ARCHPREFIX=x86_64-w64-mingw32
    CC=$ARCHPREFIX-gcc
    CXX=$ARCHPREFIX-g++
    AR=$ARCHPREFIX-ar
    LIBUDEV=no
    POSIX=no
    cfl=(-DUNICODE -D_UNICODE -m64)
    makelib () {
      $AR rcs "$@"
    }
    ;;
  osx)
    ARCHPREFIX=llvm
    CC=$ARCHPREFIX-gcc
    CXX=$ARCHPREFIX-g++
    AR=ar
    LIBUDEV=no
    cfl=(-arch i386 -arch x86_64 -mmacosx-version-min=10.7)
    makelib () {
      libtool -static -s -o "$@"
    }
    ;;
  linux)
    ARCHPREFIX=i686-loee-linux-gnu
    export PATH="/usr/local/${ARCHPREFIX}-20150122.loee.pl/bin:$PATH"
    CC=$ARCHPREFIX-gcc
    CXX=$ARCHPREFIX-g++
    AR=$ARCHPREFIX-ar
    cfl=(-D__Linux26__ -DNAME_MAX=FILENAME_MAX -m32)
    ldfl=(-lm)
    makelib () {
      $AR rcs "$@"
    }
    ;;
  linux64)
    ARCHPREFIX=x86_64-loee-linux-gnu
    export PATH="/usr/local/${ARCHPREFIX}-20150122.loee.pl/bin:$PATH"
    CC=$ARCHPREFIX-gcc
    CXX=$ARCHPREFIX-g++
    AR=$ARCHPREFIX-ar
    cfl=(-D__Linux26__ -DNAME_MAX=FILENAME_MAX -m64)
    makelib () {
      $AR rcs "$@"
    }
    ;;
  linux-armhf)
    ARCHPREFIX=arm-linux-gnueabi
    export PATH="/usr/local/arm-loee-linux-gnueabi-20150122.loee.pl/bin:$PATH"
    CC=$ARCHPREFIX-gcc
    CXX=$ARCHPREFIX-g++
    AR=$ARCHPREFIX-ar
    cfl=(-D__Linux26__ -lm)
    makelib () {
      $AR rcs "$@"
    }
    ;;
  # openwrt-i386)
  #   . ./setupwrt-i386
  #   ARCHPREFIX=i486-openwrt-linux-uclibc
  #   CC=$ARCHPREFIX-gcc
  #   AR=$ARCHPREFIX-ar
  #   DEST=out/$1
  #   LIBLUA=no
  #   cfl=(-D__Linux26__)
  #   makelib () {
  #     $AR rcs "$@"
  #   }
  #   ;;
  openwrt-mips)
    export BASE="/opt/openwrt/staging_dir"
    export STAGING_DIR="$BASE/target-mips_34kc_musl-1.1.11"
    export PATH="$BASE/toolchain-mips_34kc_gcc-4.8-linaro_musl-1.1.11/bin:$PATH"
    ARCHPREFIX=mips-openwrt-linux
    CC=$ARCHPREFIX-gcc
    CXX=$ARCHPREFIX-g++
    AR=$ARCHPREFIX-ar
    LIBLUA=no
    cfl=(-D__Linux26__ -mips16 -minterlink-mips16)
    makelib () {
      $AR rcs "$@"
    }
    ;;
  openwrt-mips-uClibc)
    #export BASE="/opt/openwrt/staging_dir"
    #export STAGING_DIR="$BASE/target-mips_34kc_uClibc-0.9.33.2"
    #export PATH="$BASE/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin:$PATH"
    export BASE="/Volumes/OpenWRT/staging_dir"
    export STAGING_DIR="$BASE/target-mips_34kc_uClibc-0.9.33.2"
    export PATH="$BASE/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin:$PATH"
    ARCHPREFIX=mips-openwrt-linux
    CC=$ARCHPREFIX-gcc
    CXX=$ARCHPREFIX-g++
    AR=$ARCHPREFIX-ar
    LIBLUA=no
    cfl=(-D__Linux26__ -mips16 -minterlink-mips16)
    makelib () {
      $AR rcs "$@"
    }
    ;;
  openwrt-mips-musl)
    export BASE="/Volumes/OpenWRT/staging_dir"
    export STAGING_DIR="$BASE/target-mips_24kc_musl"
    export PATH="$BASE/toolchain-mips_24kc_gcc-5.5.0_musl/bin:$PATH"
    ARCHPREFIX=mips-openwrt-linux
    CC=$ARCHPREFIX-gcc
    CXX=$ARCHPREFIX-g++
    AR=$ARCHPREFIX-ar
    LIBLUA=no
    #-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -mips16 -minterlink-mips16
    cfl=(-D__Linux26__ -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -mips16 -minterlink-mips16)
    makelib () {
      $AR rcs "$@"
    }
    ;;
  openwrt-arm)
    export BASE="/opt/openwrt/staging_dir"
    export STAGING_DIR="$BASE/target-arm_cortex-a8+vfpv3_musl-1.1.11_eabi"
    export PATH="$BASE/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_musl-1.1.11_eabi/bin:$PATH"
    ARCHPREFIX=arm-openwrt-linux-muslgnueabi
    CC=$ARCHPREFIX-gcc
    CXX=$ARCHPREFIX-g++
    AR=$ARCHPREFIX-ar
    LIBLUA=no
    cfl=(-D__Linux26__)
    makelib () {
      $AR rcs "$@"
    }
    ;;
  android-16-arm)
    path=(/Users/jpc/Applications/android-ndk-r9d/$ARCH/bin $path)
    ARCHPREFIX=arm-linux-androideabi
    CC=$ARCHPREFIX-gcc
    CXX=$ARCHPREFIX-g++
    AR=$ARCHPREFIX-ar
    cfl=(-D__Linux26__ -march=armv7-a -mfloat-abi=softfp)
    makelib () {
      $AR rcs "$@"
    }
    ;;
  *)
    echo "Unknown or no platform given: $1"
    exit 1
esac

if [[ "$2" = clean ]]; then
  rm -rf $DEST
elif [[ ! -z $2 ]]; then
  rm -rf $DEST/$2
fi

cfl=(-ggdb -Os --std=gnu99 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-function $cfl)
cfl=(-D_LARGEFILE64_SOURCE=1 -D_LARGEFILE_SOURCE=1 $cfl)
if [[ $LIBLUA != no ]]; then
  cfl=($cfl -Ilua-5.1.5/src)
fi
cppfl=($cfl --std=gnu++11)
TEMP=temp-$ARCH

mkdir -p $DEST

build() {
  if [[ -e $DEST/$1 ]]; then
    return
  fi
  mkdir -p $TEMP
  (build-$1) || echo "building $1 failed"
  rm -r $TEMP
}

build-liblua.a () {
  cat > $DEST/lua_compat52.h <<EOF
EOF

  [[ $LIBLUA == no ]] && return 0
  SRC=lua-5.1.5/src
    files=(lapi.c lcode.c ldebug.c ldo.c ldump.c lfunc.c lgc.c llex.c
        lmem.c lobject.c lopcodes.c lparser.c lstate.c lstring.c
        ltable.c ltm.c lundump.c lvm.c lzio.c
        lauxlib.c lbaselib.c ldblib.c liolib.c lmathlib.c loslib.c
        ltablib.c lstrlib.c loadlib.c linit.c
        print.c
#        lbitlib.c lcorolib.c lctype.c
        )

  cat > $TEMP/config.h <<EOF
#if defined(__APPLE__)
#  define LUA_USE_MACOSX
#  define LUA_USE_DLOPEN
#endif

#if defined(__linux__)
#  define LUA_USE_LINUX
#endif

#if defined(__ANDROID__)
#include <locale.h>

#define lconv rpl_lconv
struct lconv {
  char decimal_point[1];
};

#define localeconv rpl_localeconv
__attribute__((__unused__)) static struct lconv *localeconv(void)
{
  return 0;
}
#endif
EOF

  for file in $files; do
    $CC $cfl -include $TEMP/config.h -o $TEMP/${file:r}.o -c $SRC/${file:r}.c
  done

  makelib $DEST/liblua.a $TEMP/${^files:r}.o
  $CC $cfl -include $TEMP/config.h -o $DEST/luac $SRC/luac.c $DEST/liblua.a $ldfl -lm
  cp $SRC/{lauxlib,lualib,luaconf,lua}.h $DEST
}

build-liblua-socket.a() {
  SRC=luasocket/src
  files=(luasocket.o compat.o timeout.o buffer.o io.o auxiliar.o options.o inet.o
      tcp.o udp.o except.o select.o mime.o)
  if [[ $ARCH == win* ]]; then
    files=(wsocket.o $files)
  else
    files=(usocket.o unix.o unixdgram.o unixstream.o $files)
  fi

  for file in $files; do
    $CC $cfl -DNDEBUG -include $DEST/lua_compat52.h -o $TEMP/${file:r}.o -c $SRC/${file:r}.c
  done

  makelib $DEST/liblua-socket.a $TEMP/${^files}
}

build-liblua-filesystem.a() {
  SRC=luafilesystem/src

  $CC $cfl -o $TEMP/lfs.o -c $SRC/lfs.c

  makelib $DEST/liblua-filesystem.a $TEMP/lfs.o
}

build-liblua-posix.a() {
 if [[ $POSIX == no ]]; then
   return 0
 fi
 SRC=luaposix

 cat > $TEMP/config.h << EOF
#define PACKAGE_NAME "luaposix"
#define PACKAGE_STRING "luaposix 33.4.0"
#define VERSION "5.1.24"

#if defined(__ANDROID__)
#include <string.h>
#define O_DSYNC O_SYNC
extern char *mkdtemp(char *path);
int gethostid(void) { return 0; }
char *ctermid (char *buf)
{
  static char devname[] = "/dev/tty";
  if (buf == 0)
    return devname;

  return strcpy (buf, "/dev/tty");
}
#endif
EOF
 if [[ $ARCH == android* ]]; then
   wget -O $TEMP/glob.c https://raw.github.com/white-gecko/TokyoCabinet/master/glob.c
   wget -O $TEMP/glob.h https://raw.github.com/white-gecko/TokyoCabinet/master/glob.h
   $CC $cfl -I$TEMP -o $TEMP/_glob.o -c $TEMP/glob.c
 fi

 # NEW: $CC $cfl -I$TEMP -I$SRC/ext/include -o $TEMP/posix.o -c $SRC/ext/posix/posix.c
 $CC $cfl -I$TEMP -I$SRC/ext/include -o $TEMP/posix.o -c $SRC/lposix.c

 makelib $DEST/liblua-posix.a $TEMP/posix.o $TEMP/_glob.o(N)
}

build-liblua-udev.a() {
  [[ $LIBUDEV == no ]] && return 0
  SRC=lua-udev

  $CC $cfl -I$DEST -o $TEMP/udev.nobj.o -c $SRC/udev.nobj.c

  makelib $DEST/liblua-udev.a $TEMP/*.o
}

build-libev.a() {
  $CC $cfl -DNDEBUG -o $TEMP/ev.o -c ev.c
  makelib $DEST/libev.a $TEMP/ev.o
  cat > $DEST/ev.h <<EOF
#include "../../ev.h"
EOF
}

build-liblua-ev.a() {
  SRC=lua-ev

  $CC $cfl -I$DEST -o $TEMP/lua_ev.o -c $SRC/lua_ev.c

  makelib $DEST/liblua-ev.a $TEMP/*.o
}

build-liblua-md5.a() {
  SRC=md5/src
  files=(md5 md5lib compat-5.2)

  for file in $files; do
    $CC $cfl -include $DEST/lua_compat52.h -o $TEMP/$file.o -c $SRC/$file.c
  done
  makelib $DEST/liblua-md5.a $TEMP/${^files}.o
  cp $SRC/md5.h $DEST/lua-md5.h
}

build-libmodpbase64.a() {
  SRC=$PWD/stringencoders-v3.10.3/src
  types=(b2 b16 b64 burl ascii bjavascript) # FIXME: b85

  cd $TEMP

  sed -e 's/b64/b64w/g' < $SRC/modp_b64.c > modp_b64w.c
  cp $SRC/modp_b64w.h .

  case "$ARCHPREFIX" in
    mips-*)
      cat > config.h <<EOF
#define WORDS_BIGENDIAN 1
EOF
      ;;
    *)
      touch config.h
      ;;
  esac


  for type in $types; do
    gcc -o modp_${type}_gen $SRC/arraytoc.c $SRC/modp_${type}_gen.c
    ./modp_${type}_gen > modp_${type}_data.h
  done
  B64WCHARS="-_."
  ./modp_b64_gen ${B64WCHARS} > modp_b64w_data.h

  types=($types b64w numtoa)

  for type in $types; do
    srcname=modp_${type}.c
    if [[ ! -e "$srcname" ]]; then
      srcname="$SRC/$srcname"
    fi
    $CC $cfl -I. -o $type.o -c "$srcname"
  done

  cd -

  makelib $DEST/libmodpbase64.a $TEMP/${^types}.o
  cp $SRC/modp_${^types}.h $DEST
}

build-libsha2.a() {
  SRC=$PWD/sha2-07-01-07
  files=(sha1 sha2)

  for file in $files; do
    $CC $cfl -o $TEMP/$file.o -c $SRC/$file.c
  done

  makelib $DEST/libsha2.a $TEMP/${^files}.o
  mkdir -p $DEST/sha2
  cp $SRC/*.h $DEST/sha2
}

build-libudev.a() {
  if [[ $LIBUDEV == no ]]; then
    return 0
  fi
  SRC=$PWD/udev-182/src
  #pcfl=(-DENABLE_LOGGING -DENABLE_DEBUG)
  pcfl=($pcfl -include $TEMP/config.h)
  files=(libudev libudev-device libudev-device-private libudev-enumerate libudev-list libudev-monitor)
  files=($files libudev-queue libudev-queue-private libudev-util libudev-util-private)

cat > $TEMP/config.h <<EOF
#define _GNU_SOURCE

#define SYSCONFDIR "/etc"
#define PKGLIBEXECDIR "/lib/udev"

#if defined(__ANDROID__)
#include "fcntl.h"
#define SOCK_NONBLOCK O_NONBLOCK
#define SOCK_CLOEXEC O_CLOEXEC
#endif

#define MAX(a,b) ({ __typeof__ (a) _a = (a); __typeof__ (b) _b = (b);  _a > _b ? _a : _b; })
#define MIN(a,b) ({ __typeof__ (a) _a = (a); __typeof__ (b) _b = (b);  _a < _b ? _a : _b; })
EOF

  for file in $files; do
    $CC $cfl $pcfl -o $TEMP/$file.o -c $SRC/$file.c
  done

  cat > $TEMP/mempcpy.c <<EOF
#include <string.h>

void *mempcpy(void *dest, const void *src, size_t n) {
  memcpy(dest, src, n);
  dest += n;
  return dest;
}
EOF
  $CC $cfl $pcfl -o $TEMP/mempcpy.o -c $TEMP/mempcpy.c

  makelib $DEST/libudev.a $TEMP/${^files}.o $TEMP/mempcpy.o
  cp $SRC/libudev.h $DEST/
}

build-liblua-winapi.a () {
  if [[ $ARCH != win* ]]; then
    return 0
  fi
  SRC=$PWD/winapi
  files=(winapi wutils)
  cfl=(${cfl:#*UNICODE*} -DPSAPI_VERSION=1)

  for file in $files; do
    $CC $cfl -o $TEMP/$file.o -c $SRC/$file.c
  done

  makelib $DEST/liblua-winapi.a $TEMP/${^files}.o
}

build-libluachecks.a () {
  SRC=luasched/c

  $CC $cfl $flags -o $TEMP/checks.o -c $SRC/checks.c
  makelib $DEST/libluachecks.a $TEMP/checks.o
}

build-liblua-lpeg.a () {
  SRC=lpeg
  files=(lpvm lpcap lptree lpcode lpprint)

  for file in $files; do
    $CC $cfl -I$DEST -o $TEMP/$file.o -c $SRC/$file.c
  done

  makelib $DEST/liblua-lpeg.a $TEMP/${^files}.o
}

build-liblua-cjson.a () {
  SRC=$PWD/lua-cjson
  files=(lua_cjson fpconv strbuf)

  for file in $files; do
    $CC $cfl -o $TEMP/$file.o -c $SRC/$file.c
  done

  makelib $DEST/liblua-cjson.a $TEMP/${^files}.o
}

build-liblua-tweetnacl.a () {
  SRC=$PWD/luatweetnacl
  files=(luatweetnacl randombytes tweetnacl)

  for file in $files; do
    $CC $cfl -o $TEMP/$file.o -c $SRC/$file.c
  done

  makelib $DEST/liblua-tweetnacl.a $TEMP/${^files}.o
}

build libev.a
build libmodpbase64.a
build libsha2.a
build libudev.a

build liblua.a
build liblua-socket.a
build liblua-filesystem.a
build liblua-md5.a
build liblua-winapi.a
build liblua-udev.a
build liblua-ev.a
build liblua-posix.a
build libluachecks.a
build liblua-lpeg.a
build liblua-cjson.a
build liblua-tweetnacl.a
