#!/bin/sh

CFLAGS="-ggdb -Os --std=gnu99 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-function -D_LARGEFILE64_SOURCE=1 -D_LARGEFILE_SOURCE=1"
export CPPFLAGS="--std=gnu++11"

CFLAGS="$CFLAGS -arch x86_64 -arch arm64 -mmacosx-version-min=10.10" LDFLAGS="-arch x86_64 -arch arm64 -mmacosx-version-min=10.10" \
  ./new-osx-toolchain toolchains/osx

CFLAGS="$CFLAGS -DUNICODE -D_UNICODE" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/i686-w64-mingw32-2021-03-20 i686-w64-mingw32 toolchains/win32 windows
CFLAGS="$CFLAGS -DUNICODE -D_UNICODE" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/x86_64-w64-mingw32-2021-03-20 x86_64-w64-mingw32 toolchains/win64 windows

CFLAGS="$CFLAGS -D__Linux26__ -DNAME_MAX=FILENAME_MAX -m32" LDFLAGS="-lm" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/i686-loee-linux-gnu-2021-03-20 i686-loee-linux-gnu toolchains/linux linux
CFLAGS="$CFLAGS -D__Linux26__ -DNAME_MAX=FILENAME_MAX -m64" LDFLAGS="-lm" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/x86_64-loee-linux-gnu-2021-03-20 x86_64-loee-linux-gnu toolchains/linux64 linux
CFLAGS="$CFLAGS -D__Linux26__ -DNAME_MAX=FILENAME_MAX" LDFLAGS="-lm" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/aarch64-loee-linux-gnu-2021-03-20 aarch64-loee-linux-gnu toolchains/linux-arm64 linux
CFLAGS="$CFLAGS -D__Linux26__ -DNAME_MAX=FILENAME_MAX" LDFLAGS="-lm" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/armv7-loee-linux-gnueabihf-2021-03-20 armv7-loee-linux-gnueabihf toolchains/linux-armhf linux
CFLAGS="$CFLAGS -D__Linux26__ -DNAME_MAX=FILENAME_MAX" LDFLAGS="-lm" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/arm-loee-linux-gnueabi-2021-03-20 arm-loee-linux-gnueabi toolchains/linux-armv5 linux

CFLAGS="$CFLAGS -D__Linux26__ -DNAME_MAX=FILENAME_MAX -m64" LDFLAGS="-lm" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/x86_64-loee-linux-musl-2021-03-20 x86_64-loee-linux-musl toolchains/linux64-musl linux
CFLAGS="$CFLAGS -D__Linux26__ -DNAME_MAX=FILENAME_MAX" LDFLAGS="-lm" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/aarch64-loee-linux-musl-2021-03-20 aarch64-loee-linux-musl toolchains/linux-arm64-musl linux

CFLAGS="$CFLAGS -D__Linux26__ -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -msoft-float -mips16 -minterlink-mips16" LDFLAGS="-lm" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/mips-loee-linux-musl-2021-03-20 mips-loee-linux-musl toolchains/openwrt-mips linux
CFLAGS="$CFLAGS -D__Linux26__ -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -msoft-float -mips16 -minterlink-mips16" LDFLAGS="-lm" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/mipsel-loee-linux-musl-2021-03-20 mipsel-loee-linux-musl toolchains/openwrt-mipsel linux
CFLAGS="$CFLAGS -D__Linux26__ -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -msoft-float -mips16 -minterlink-mips16" LDFLAGS="-lm" \
  ./new-crosstool-toolchain /usr/local/cross.loee.pl/mipsel-loee-linux-gnu-2021-03-20 mipsel-loee-linux-gnu toolchains/linux-mipsel linux

